# Generated by Django 4.2.5 on 2023-09-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='brand_category_message',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
