# Generated by Django 4.2.5 on 2023-09-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
